# Generated by Django 4.2.1 on 2023-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linear_regr_model',
            field=models.FileField(blank=True, upload_to='ml_model'),
        ),
    ]
