# Generated by Django 4.2.1 on 2023-05-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_company_linear_regr_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='linear_regr_model',
        ),
    ]
