# Generated by Django 4.2.1 on 2023-05-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_company_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Название компании', 'verbose_name_plural': 'Название компаний'},
        ),
    ]
